#include "stdafx.h"
#include "GUI.h"
#include "CIGRuleConfig.h"

namespace CIG
{
	bool CIG::CIGRuleConfig::checkConstrains()
	{
		typedef unsigned long long U64;
		if (PLAYER_NUM != 2)
		{
			ostringstream oss;
			oss << "暂时不支持多人游戏. \n" ;
			GUI::inform(oss.str(), true);
			return false;
		}

		return true;
	}

	const float CIGRuleConfig::TIME_LIMIT = -1;

	const CIGRuleConfig::CHESS_OPERATIONS CIGRuleConfig::chessOperationGraph[NOMORE_CHESS_OPERATION][NOMORE_CHESS_OPERATION + 1] =
	{
		{NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION},
		{NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION},
		{NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION},
		{NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION},
		{NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION},
		{NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION},
		{NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION, NOMORE_CHESS_OPERATION},
	};

	const CIGRuleConfig::PLAYER_OPERATIONS CIGRuleConfig::playerOperationGraph[NOMORE_PLAYER_OPERATIONS][NOMORE_PLAYER_OPERATIONS+1]= 
	{
		{ADD, NOMORE_PLAYER_OPERATIONS, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, },
		{PUT_PLAYER, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, },
		{END_PLAYER, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, },
		{NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION, NOMORE_PLAYER_OPERATION},
	};


	const CIGRuleConfig::CHESSMAN_TYPES CIGRuleConfig::INI_BOARD[PLAYER_NUM][1 << INI_BOARD_HEIGHT_LOG2][1 << INI_BOARD_WIDTH_LOG2] =
	{
		{
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  /*NOCHESSMAN*/CHESS,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
		},
		{
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  /*NOCHESSMAN*/CHESS,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
			{NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,  NOCHESSMAN,							},
		}
	};

	const bool CIGRuleConfig::BOARD_RANGE[1 << INI_BOARD_HEIGHT_LOG2][1 << INI_BOARD_WIDTH_LOG2] =
	{
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, },
		{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
	};
}
